In [2]:
import pandas as pd
import numpy as np
import math

In [3]:
pd.set_option('display.max_columns', None)

In [ ]:
/home/gomosak/conafor/SEByc/linear_regression/ciclo1_out.csv

In [4]:
df = pd.read_csv("../linear_regression/ciclo1_out.csv", low_memory=False, index_col = 'id')

In [5]:
df1 = pd.read_csv("../csvs/ciclo_1.csv", low_memory=False, index_col = 'id')

In [ ]:
altura en tocones .3
diametro en tocones 10 
grado putrefaccion tocones

In [6]:
len(df)

1305130

In [7]:
len(df1)

1305130

In [12]:
df.head()

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,0.0,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,0.0,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN

In [10]:
df1.head()

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN

In [11]:
n = len(df1)
zeros = np.empty(n, dtype=object)

In [17]:
df1.insert(15, 'is_predicted', zeros)

In [18]:
df1.head()

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,None,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,None,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,None,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,None,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,None,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN

In [9]:
df1["volumen_eq"] = zeros
df1["biomasa_eq"] = zeros
df1["densidad_eq"] = zeros
df1["volumen"] = zeros
df1["biomasa"] = zeros
df1["carbono"] = zeros

In [10]:
df1.head()

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad,volumen_eq,biomasa_eq,densidad_eq,volumen,biomasa,carbono
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2886174,2016,50760,1,Vivo,NaN,Malvaceae,Hampea,trilobata,NaN,NaN,14,16.0,NaN,8.3,6.4,20.622,-87.336694,15.2,SMQ,493302,16,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN,None,None,None,None,None,None
2886175,2016,50760,1,Vivo,NaN,Nyctaginaceae,Neea,psychotrioides,NaN,NaN,21,23.0,NaN,10.4,8.6,20.622,-87.336694,15.2,SMQ,493309,23,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN,None,None,None,None,None,None
2886176,2016,50760,1,Vivo,NaN,Fabaceae,Lysiloma,latisiliquum,NaN,NaN,29,34.0,NaN,32.8,10.3,20.622,-87.336694,15.2,SMQ,493320,34,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN,None,None,None,None,None,None
2886177,2016,50760,1,Vivo,NaN,Malvaceae,Luehea,speciosa,NaN,NaN,35,40.0,NaN,8.2,7.9,20.622,-87.336694,15.2,SMQ,493326,40,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN,None,None,None,None,None,None
2886178,2016,50760,1,Vivo,NaN,Sapotaceae,Sideroxylon,salicifolium,NaN,NaN,44,49.0,NaN,9.8,6.8,20.622,-87.336694,15.2,SMQ,493335,49,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN,None,None,None,None,None,None

In [19]:
df.index

Index([      1,       2,       3,       4,       5,       6,       7,       8,
             9,      10,
       ...
       1305121, 1305122, 1305123, 1305124, 1305125, 1305126, 1305127, 1305128,
       1305129, 1305130],
      dtype='int64', name='id', length=1247932)

In [20]:
df1.loc[df.index] = df

In [21]:
df1

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,0.0,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,0.0,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305126,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,6,NaN,NaN,31.5,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267537,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305127,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,7,NaN,NaN,35.3,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267536,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305128,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,8,NaN,NaN,30.0,19.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267535,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305129,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,9,NaN,NaN,30.0,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267533,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305130,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,10,NaN,NaN,48.0,22.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267534,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN

In [14]:
df1[df1.condicion == "Tocón"]

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad,volumen_eq,biomasa_eq,densidad_eq,volumen,biomasa,carbono
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2886290,2019,75163,4,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,3,3.0,NaN,13.0,0.40,16.658000,-96.623583,14.4,BQ,857537,3,NaN,NaN,NaN,2.0,14,14.4.3,14.4.3.3,20,Oaxaca,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.55615,0.005309,1.47638,0.821089
2886304,2016,50545,1,Tocón,NaN,Fagaceae,Quercus,magnoliifolia,NaN,NaN,10,10.0,NaN,36.5,NaN,21.302167,-104.766583,13.4,BQP,475352,10,NaN,NaN,NaN,3.0,13,13.4.2,13.4.2.2,18,Nayarit,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.69025,NaN,NaN,NaN
2886305,2016,50545,1,Tocón,NaN,Fagaceae,Quercus,magnoliifolia,NaN,NaN,13,13.0,NaN,13.2,0.31,21.302167,-104.766583,13.4,BQP,475355,13,NaN,NaN,NaN,3.0,13,13.4.2,13.4.2.2,18,Nayarit,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.69025,0.004242,1.464116,1.010606
2886399,2016,50078,1,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,1,1.0,NaN,13.8,NaN,21.387500,-105.058917,15.5,SMQ,521110,1,NaN,NaN,NaN,2.0,15,15.5.2,15.5.2.2,18,Nayarit,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.5712,NaN,NaN,NaN
2886400,2016,50078,1,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,5,5.0,NaN,11.8,NaN,21.387500,-105.058917,15.5,SMQ,521114,5,NaN,NaN,NaN,2.0,15,15.5.2,15.5.2.2,18,Nayarit,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.5712,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717203,2015,50197,2,Tocón,NaN,Fagaceae,Quercus,rugosa,NaN,NaN,2,2.0,NaN,12.5,0.50,21.394111,-99.293306,13.3,BQ,246211,2,NaN,NaN,NaN,NaN,13,13.3.1,13.3.1.1,22,Querétaro,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.65041,0.006136,1.995431,1.297848
3717285,2016,75151,3,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,7,7.0,NaN,39.1,NaN,16.677333,-97.184944,13.5,BP,523384,7,NaN,NaN,NaN,4.0,13,13.5.2,13.5.2.1,20,Oaxaca,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.57424,NaN,NaN,NaN
3717293,2019,49821,4,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,26,26.0,NaN,25.5,0.40,20.866306,-87.989278,15.2,SMS,859238,26,NaN,NaN,NaN,4.0,15,15.2.1,15.2.1.1,31,Yucatán,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.61222,0.020428,6.253273,3.828379
3717350,2016,50148,2,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,3,12.0,NaN,22.7,0.40,21.417778,-101.667278,12.2,BQP,521231,12,NaN,NaN,NaN,3.0,12,12.2.1,12.2.1.2,14,Jalisco,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.59768,0.016188,4.837711,2.891403
3717383,2017,50179,1,Tocón,NaN,ZZ Familia Desconocida,ZZ Genero Desconocido,NaN,NaN,NaN,23,24.0,NaN,54.3,0.37,21.406944,-100.165333,13.3,BQP,654372,24,NaN,NaN,NaN,3.0,13,13.3.1,13.3.1.1,11,Guanajuato,NaN,(3.14159 * (([d130] / 2 / 100) ** 2) * [ht]),1000 * ([p] * [v])*(3/6),0.58924,0.085682,25.243707,14.874602

In [38]:
df1[(df1.genero == "Pinus") & (df1.epiteto == "montezumae")]

,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad,volumen_eq,biomasa_eq,densidad_eq,volumen,biomasa,carbono
id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2886402,2019,50081,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,7,7.0,NaN,30.1,21.2,21.390278,-104.913806,13.4,BQP,842224,7,NaN,NaN,NaN,NaN,13,13.4.2,13.4.2.4,18,Nayarit,NaN,NaN,(0.013)*([d130]**3.046),0.43329,0.0,414.626349,179.653451
2886578,2015,50564,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,9,9.0,NaN,30.2,14.8,21.316167,-103.846500,13.2,BPQ,116451,9,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,362.369195,157.010948
2887034,2015,50564,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,8,8.0,NaN,36.4,20.4,21.316167,-103.846500,13.2,BPQ,116450,8,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,685.934206,297.208432
2888644,2017,50099,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,2,3.0,NaN,18.7,10.1,21.404417,-104.041500,13.2,BPQ,650827,3,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,105.692509,45.795507
2888645,2017,50099,4,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,6,7.0,NaN,45.7,25.0,21.404417,-104.041500,13.2,BPQ,650850,7,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,1256.205924,544.301465
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3707714,2015,50564,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,2,2.0,NaN,48.9,23.6,21.316167,-103.846500,13.2,BPQ,116444,2,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,1349.223222,584.60493
3709967,2019,50081,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,1,1.0,NaN,36.2,24.5,21.390278,-104.913806,13.4,BQP,842218,1,NaN,NaN,NaN,NaN,13,13.4.2,13.4.2.4,18,Nayarit,NaN,NaN,(0.013)*([d130]**3.046),0.43329,0.0,727.393906,315.172505
3711997,2017,50779,4,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,3,3.0,NaN,49.5,13.7,21.260250,-104.571806,13.4,BPQ,629652,3,NaN,NaN,NaN,NaN,13,13.4.2,13.4.2.2,18,Nayarit,NaN,NaN,(0.013)*([d130]**3.046),0.43329,0.0,1886.734489,817.503187
3712188,2015,50811,3,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,1,1.0,NaN,44.8,17.3,21.278583,-103.023194,13.2,BQP,161299,1,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,32,Zacatecas,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,863.458267,374.127833
3713310,2017,50099,4,Vivo,NaN,Pinaceae,Pinus,montezumae,NaN,NaN,5,6.0,NaN,33.9,23.0,21.404417,-104.041500,13.2,BPQ,650849,6,NaN,NaN,NaN,NaN,13,13.2.1,13.2.1.1,18,Nayarit,NaN,NaN,(0.058)*((([d130]**2)*[ht])**0.919),0.43329,0.0,671.99017,291.166621

In [39]:
(0.006*30.1**3.038)

186.22426291820673