In [1]:
import pandas as pd
import numpy as np
import re

In [2]:
import sys
from pathlib import Path

# Add the parent directory to sys.path
sys.path.append(str(Path().resolve().parent))

# Now import the module
from normalization.conditions import assign_equations, volumen

In [3]:
pd.set_option('display.max_columns', None)

In [4]:
df_original = pd.read_csv('../csvs/ciclo_1.csv', low_memory=False)
modelos = pd.read_excel('../csvs/modelos.xlsx')
df_regression = pd.read_csv('../linear_regression/ciclo1_out.csv',low_memory=False)
print("All the files where opened correctly")

All the files where opened correctly

In [5]:
n = len(df_original)
is_predicted = np.zeros(n)
df_original.insert(16, 'is_predicted', is_predicted)
print("Insertion correctly")

Insertion correctly

In [6]:
index = df_regression.index
df_original.loc[index] = df_regression
print("The original was changed for regression data")

The original was changed for regression data

In [7]:
df_original.loc[(df_original.condicion == "Tocón") & (df_original.altura <= 0) , "altura"] = .3
df_original.loc[(df_original.condicion == "Tocón") & (df_original.altura.isnull()), "altura"] = .3

df_original.loc[(df_original.condicion == "Tocón") & (df_original.diametro <= 0), "diametro"] = 7.5
df_original.loc[(df_original.condicion == "Tocón") & (df_original.diametro.isnull()), "diametro"] = .3


df_original.loc[(df_original.condicion != "Tocón") & (df_original.diametro.isnull()), "diametro"] = 7.5
df_original.loc[(df_original.condicion != "Tocón") & (df_original.altura.isnull()), "altura"] = 1.3

#b_eq = np.empty(n, dtype=object)

In [8]:
df_original

,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
0,1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,0.0,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
1,2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,0.0,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
3,4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
4,5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305125,1305126,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,6,NaN,NaN,31.5,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267537,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305126,1305127,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,7,NaN,NaN,35.3,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267536,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305127,1305128,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,8,NaN,NaN,30.0,19.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267535,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305128,1305129,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,9,NaN,NaN,30.0,20.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267533,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN
1305129,1305130,2005,78002,4,Vivo,19494.0,Rhizophoraceae,Rhizophora,mangle,NaN,NaN,10,NaN,NaN,48.0,22.00,0.0,14.587356,-92.270686,15.6,VHL,caracteristica_arbolado,1267534,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,15,15.6.1,15.6.1.1,7,Chiapas,NaN

In [9]:
df_original.iloc[:10]

,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
0,1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.300000,3.20,0.0,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
1,2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.000000,5.50,0.0,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.000000,5.50,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
3,4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.500000,5.85,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
4,5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.000000,6.25,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
5,6,2005,153,1,Vivo,7758.0,Cupressaceae,Juniperus,californica,NaN,NaN,4,NaN,NaN,13.500000,3.20,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,4,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
6,7,2005,153,1,Vivo,2270.0,Cupressaceae,Juniperus,NaN,NaN,NaN,5,NaN,NaN,13.500000,3.00,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,5,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
7,8,2005,153,1,Vivo,2270.0,Cupressaceae,Juniperus,NaN,NaN,NaN,6,NaN,NaN,9.000000,2.90,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,6,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
8,9,2005,153,1,Vivo,2270.0,Cupressaceae,Juniperus,NaN,NaN,NaN,7,NaN,NaN,9.500000,3.00,0.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,7,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN
9,10,2005,153,1,Vivo,2270.0,Cupressaceae,Juniperus,NaN,NaN,NaN,8,NaN,NaN,11.588285,3.50,2.0,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,8,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN

In [10]:
df_10 = df_original.iloc[:10]

In [11]:
b_eq = assign_equations(df_10, modelos, variable_resultado="b", conditions="biomasa")

  0%|                                                    | 0/10 [00:00<?, ?it/s]

NameError: name 're' is not defined

In [13]:
b_eq

,id,id_anterior,variable_resultado,tipo,ecuacion,ecuacion_php,especie_id,familia,genero,epiteto,condicion,componente,diametro_min,diametro_max,numero_arboles,r2,anio_publicacion,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n2,clave_ecoregion_n3,clave_ecoregion_n4,clave_bur,clave_estado_inegi,activo,id_especie_mn,id_modelo_mn,referencia,id_referencia,notas
114,115,109.0,b,General,(GE*(Exp((-1.499 )+(2.148*(LN(d130)))+((0.2079...,(GE*(Exp((-1.499 )+(2.148*(LOG([d130])))+((0.2...,NaN,NaN,NaN,NaN,Vivo,Todo el árbol,5.0,138.0,1501.0,0.95,2005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,253.0,Ecuaciones Rojas,99.0,"Se depuraron las ecuaciones generales, mas aba..."
115,116,110.0,b,General,(GE*Exp((-1.239)+(1.98*LN((d130)))+ (0.207*(LN...,(GE*Exp((-1.239)+(1.98*LOG(([d130])))+ (0.207*...,NaN,NaN,NaN,NaN,Vivo,Todo el árbol,5.0,63.4,415.0,0.95,2005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,628.0,Ecuaciones Rojas,100.0,"Se depuraron las ecuaciones generales, mas aba..."
116,117,111.0,b,General,(GE*(Exp((-0.667)+(1.784*(LN(d130)))+ (0.207*(...,(GE*(Exp((-0.667)+(1.784*(LOG([d130])))+ (0.20...,NaN,NaN,NaN,NaN,Vivo,Todo el árbol,5.0,63.4,401.0,0.95,2005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,255.0,Ecuaciones Rojas,101.0,"Se depuraron las ecuaciones generales, mas aba..."
117,118,112.0,b,General,(GE*Exp((-1.349)+(1.98*LN((d130)))+ (0.207*(LN...,(GE*Exp((-1.349)+(1.98*LOG(([d130])))+ (0.207*...,NaN,NaN,NaN,NaN,Vivo,Todo el árbol,5.0,42.0,415.0,0.95,2005.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,254.0,Ecuaciones Rojas,102.0,"Se depuraron las ecuaciones generales, mas aba..."
455,456,440.0,b,General,(Exp(-2.187+(0.916*(LN((p)*((d130)^2)*(ht)))))),(Exp(-2.187+(0.916*(LOG(([p])*(([d130])**2)*([...,NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,9.0,9.5,9.5.1,9.5.1.2,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,1.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
556,557,541.0,b,General,(Exp(-2.977+LN((p)*((d130)^2)*(ht)))),(Exp(-2.977+LOG(([p])*(([d130])**2)*([ht])))),NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.1,15.1.2,15.1.2.1,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,10.0,NaN
557,558,542.0,b,General,(Exp(-2.977+LN((p)*((d130)^2)*(ht)))),(Exp(-2.977+LOG(([p])*(([d130])**2)*([ht])))),NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.2,15.2.2,15.2.2.1,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,10.0,NaN
558,559,543.0,b,General,(Exp(-2.977+LN((p)*((d130)^2)*(ht)))),(Exp(-2.977+LOG(([p])*(([d130])**2)*([ht])))),NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.5,15.5.1,15.5.1.1,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,10.0,NaN
559,560,544.0,b,General,(Exp(-2.977+LN((p)*((d130)^2)*(ht)))),(Exp(-2.977+LOG(([p])*(([d130])**2)*([ht])))),NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.5,15.5.2,15.5.2.1,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,10.0,NaN
560,561,545.0,b,General,(Exp(-2.977+LN((p)*((d130)^2)*(ht)))),(Exp(-2.977+LOG(([p])*(([d130])**2)*([ht])))),NaN,NaN,NaN,NaN,Vivo,Todo el árbol,NaN,NaN,NaN,NaN,NaN,NaN,15.0,15.6,15.6.1,15.6.1.1,NaN,NaN,1,NaN,NaN,Ecuaciones Chave,10.0,NaN

In [22]:
b_eq.loc[117]

id                                                                  118
id_anterior                                                       112.0
variable_resultado                                                    b
tipo                                                            General
ecuacion              (GE*Exp((-1.349)+(1.98*LN((d130)))+ (0.207*(LN...
ecuacion_php          (GE*Exp((-1.349)+(1.98*LOG(([d130])))+ (0.207*...
especie_id                                                          NaN
familia                                                             NaN
genero                                                              NaN
epiteto                                                             NaN
condicion                                                          Vivo
componente                                                Todo el árbol
diametro_min                                                        5.0
diametro_max                                                       42.0
numero_arboles                                                    415.0
r2                                                                 0.95
anio_publicacion                                                 2005.0
grado_putrefaccion                                                  NaN
clave_ecoregion_n1                                                  NaN
clave_ecoregion_n2                                                  NaN
clave_ecoregion_n3                                                  NaN
clave_ecoregion_n4                                                  NaN
clave_bur                                                           NaN
clave_estado_inegi                                                  NaN
activo                                                                0
id_especie_mn                                                       NaN
id_modelo_mn                                                      254.0
referencia                                             Ecuaciones Rojas
id_referencia                                                     102.0
notas                 Se depuraron las ecuaciones generales, mas aba...
Name: 117, dtype: object

In [23]:
(b_eq['grado_putrefaccion']).idxmin()

/tmp/ipykernel_14778/303704464.py:1: FutureWarning: The behavior of Series.idxmin with all-NA values, or any-NA and skipna=False, is deprecated. In a future version this will raise ValueError
  (b_eq['grado_putrefaccion']).idxmin()

nan

In [ ]:
def count_variables(expression):
    potential_vars = re.findall(r'\b[a-zA-Z_]\w*\b', expression)
    functions_and_constants = {'Exp', 'LN'}
    variables = [var for var in potential_vars if var not in functions_and_constants]
    unique_variables = set(variables)
    return len(unique_variables)

variable_counts = b_eq['ecuacion'].apply(count_variables)

# Find the index of the row with the maximum number of variables
max_variable_index = variable_counts.idxmax()


rango = (b_eq['diametro_max'] - b_eq['diametro_min']).idxmin()
radio = (b_eq['r2']).idxmax()
arboles = (b_eq['numero_arboles']).idxmax()
variables = max_variable_index
if not np.isnan(rango):
    return b_eq.loc[rango]
elif not np.isnan(radio):
    return b_eq.loc[radio]
elif not np.isnan(arboles):
    return b_eq.loc[arboles]
elif not np.isnan(variables):
    return b_eq.iloc[variables]
else:
    return "This does not have eq that match the conditions"

In [48]:
def find_max_criteria_row(df):
    """
    Finds the row in the DataFrame `df` that satisfies the maximum or minimum criteria for 
    several specific columns. It checks for the following criteria in order:
    
    1. The minimum difference between 'diametro_max' and 'diametro_min'.
    2. The maximum value in the 'r2' column.
    3. The maximum value in the 'numero_arboles' column.
    4. The maximum number of unique variables in the 'ecuacion' column.
    
    The function returns the first row that satisfies any of these criteria.

    Parameters:
    ----------
    df : pandas.DataFrame
        The DataFrame containing the columns 'diametro_max', 'diametro_min', 'r2', 'numero_arboles', 
        and 'ecuacion'.

    Returns:
    -------
    pandas.Series or str
        The row from the DataFrame that meets the first of the specified criteria.
        If no criteria are met, it returns a message indicating no matches.
    """

    def count_variables(expression):
        """
        Counts the number of unique variables in a mathematical expression.

        Parameters:
        ----------
        expression : str
            The mathematical expression as a string.

        Returns:
        -------
        int
            The number of unique variables in the expression.
        """
        potential_vars = re.findall(r'\b[a-zA-Z_]\w*\b', expression)
        functions_and_constants = {'Exp', 'LN'}
        variables = [var for var in potential_vars if var not in functions_and_constants]
        unique_variables = set(variables)
        return len(unique_variables)

    # Calculate variable counts for each row in the 'ecuacion' column
    variable_counts = df['ecuacion'].apply(count_variables)

    # Find indices for the specified criteria
    indices = [
        (df['diametro_max'] - df['diametro_min']).idxmin(),  # Minimum range
        df['r2'].idxmax(),                                   # Maximum r2
        df['numero_arboles'].idxmax(),                       # Maximum number of trees
        variable_counts.idxmax()                             # Maximum variables
    ]

    # Iterate over indices and return the first valid row
    for index in indices:
        if not np.isnan(index):
            return df.loc[index]

    # If no valid index is found, return a message
    return "This does not have eq that match the conditions"

In [49]:
# Example usage with a DataFrame b_eq
result = find_max_criteria_row(b_eq)
print(result)

id                                                                  118
id_anterior                                                       112.0
variable_resultado                                                    b
tipo                                                            General
ecuacion              (GE*Exp((-1.349)+(1.98*LN((d130)))+ (0.207*(LN...
ecuacion_php          (GE*Exp((-1.349)+(1.98*LOG(([d130])))+ (0.207*...
especie_id                                                          NaN
familia                                                             NaN
genero                                                              NaN
epiteto                                                             NaN
condicion                                                          Vivo
componente                                                Todo el árbol
diametro_min                                                        5.0
diametro_max                                                       42.0
numero_arboles                                                    415.0
r2                                                                 0.95
anio_publicacion                                                 2005.0
grado_putrefaccion                                                  NaN
clave_ecoregion_n1                                                  NaN
clave_ecoregion_n2                                                  NaN
clave_ecoregion_n3                                                  NaN
clave_ecoregion_n4                                                  NaN
clave_bur                                                           NaN
clave_estado_inegi                                                  NaN
activo                                                                0
id_especie_mn                                                       NaN
id_modelo_mn                                                      254.0
referencia                                             Ecuaciones Rojas
id_referencia                                                     102.0
notas                 Se depuraron las ecuaciones generales, mas aba...
Name: 117, dtype: object

In [ ]:
#c_eq = assign_equations(df_original, modelos, variable_resultado="c", conditions="carbono")
#p_eq = assign_equations(df_original, modelos, variable_resultado="p", conditions="densidad")

#df_original_muerto = df_original[df_original.condicion == "Muertos"]
#df_original_tocon = df_original[df_original.condicion == "Tocón"]

#v_eq = volumen(df_original_muerto, df_original_tocon, modelos)


np.save('b_eq.npy', b_eq)