In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
pd.set_option('display.max_columns', None)

In [3]:
df = pd.read_csv("csvs/arboles.csv")

/tmp/ipykernel_11651/943680803.py:1: DtypeWarning: Columns (9,10,20,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("csvs/arboles.csv")

In [4]:
df.head()

,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
0,1,2005,60,1,Vivo,680.0,Ericaceae,Arctostaphylos,NaN,NaN,NaN,1,NaN,3.0,8.3,3.20,32.515597,-116.350450,11.1,MXL,caracteristica_vegetacion_mayor,107497,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
1,2,2005,64,4,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,0.0,14.0,5.50,32.532903,-116.140585,11.1,MXL,caracteristica_vegetacion_mayor,101063,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.1,11.1.1.3,2,Baja California,NaN
2,3,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,1,NaN,NaN,17.0,5.50,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,1,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,74.0
3,4,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,2,NaN,NaN,14.5,5.85,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,2,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,61.0
4,5,2005,153,1,Vivo,26426.0,Pinaceae,Pinus,quadrifolia,NaN,NaN,3,NaN,NaN,21.0,6.25,32.448351,-116.077138,11.1,BCO,caracteristica_arbolado,3,1.0,2019-11-14 20:24:49.070,2019-11-14 20:24:49.070,NaN,11,11.1.3,11.1.3.1,2,Baja California,NaN

In [5]:
df3 = df[(df.anio_levantamiento >= 2015) & (df.anio_levantamiento <= 2020)]

In [6]:
df3.head()

,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
2886148,2886174,2016,50760,1,Vivo,NaN,Malvaceae,Hampea,trilobata,NaN,NaN,14,16.0,NaN,8.3,6.4,20.622,-87.336694,15.2,SMQ,493302,16,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886149,2886175,2016,50760,1,Vivo,NaN,Nyctaginaceae,Neea,psychotrioides,NaN,NaN,21,23.0,NaN,10.4,8.6,20.622,-87.336694,15.2,SMQ,493309,23,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886150,2886176,2016,50760,1,Vivo,NaN,Fabaceae,Lysiloma,latisiliquum,NaN,NaN,29,34.0,NaN,32.8,10.3,20.622,-87.336694,15.2,SMQ,493320,34,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886151,2886177,2016,50760,1,Vivo,NaN,Malvaceae,Luehea,speciosa,NaN,NaN,35,40.0,NaN,8.2,7.9,20.622,-87.336694,15.2,SMQ,493326,40,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886152,2886178,2016,50760,1,Vivo,NaN,Sapotaceae,Sideroxylon,salicifolium,NaN,NaN,44,49.0,NaN,9.8,6.8,20.622,-87.336694,15.2,SMQ,493335,49,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN

In [7]:
df3

,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
2886148,2886174,2016,50760,1,Vivo,NaN,Malvaceae,Hampea,trilobata,NaN,NaN,14,16.0,NaN,8.3,6.4,20.622000,-87.336694,15.2,SMQ,493302,16,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886149,2886175,2016,50760,1,Vivo,NaN,Nyctaginaceae,Neea,psychotrioides,NaN,NaN,21,23.0,NaN,10.4,8.6,20.622000,-87.336694,15.2,SMQ,493309,23,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886150,2886176,2016,50760,1,Vivo,NaN,Fabaceae,Lysiloma,latisiliquum,NaN,NaN,29,34.0,NaN,32.8,10.3,20.622000,-87.336694,15.2,SMQ,493320,34,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886151,2886177,2016,50760,1,Vivo,NaN,Malvaceae,Luehea,speciosa,NaN,NaN,35,40.0,NaN,8.2,7.9,20.622000,-87.336694,15.2,SMQ,493326,40,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
2886152,2886178,2016,50760,1,Vivo,NaN,Sapotaceae,Sideroxylon,salicifolium,NaN,NaN,44,49.0,NaN,9.8,6.8,20.622000,-87.336694,15.2,SMQ,493335,49,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3717474,3717500,2016,50303,1,Vivo,NaN,Fabaceae,Caesalpinia,platyloba,NaN,NaN,6,6.0,NaN,17.8,9.1,20.693639,-87.135167,15.2,SMQ,523099,6,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
3717475,3717501,2016,50303,2,Vivo,NaN,Fabaceae,Swartzia,cubensis,NaN,NaN,12,13.0,NaN,8.3,7.8,20.693639,-87.135167,15.2,SMQ,523135,13,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
3717476,3717502,2016,50303,2,Vivo,NaN,Arecaceae,Sabal,yapa,NaN,NaN,13,14.0,NaN,17.7,10.3,20.693639,-87.135167,15.2,SMQ,523136,14,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
3717477,3717503,2016,50303,2,Vivo,NaN,Sapotaceae,Manilkara,zapota,NaN,NaN,24,25.0,NaN,32.3,9.1,20.693639,-87.135167,15.2,SMQ,523147,25,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN
3717478,3717504,2016,50303,2,Vivo,NaN,Anacardiaceae,Metopium,brownei,NaN,NaN,9,10.0,NaN,8.4,7.7,20.693639,-87.135167,15.2,SMQ,523132,10,NaN,NaN,NaN,NaN,15,15.2.2,15.2.2.2,23,Quintana Roo,NaN

In [7]:
df3.to_csv("arboles_2015.csv",index=False)

In [50]:
df = pd.read_csv("out.csv")

/tmp/ipykernel_7706/3238720368.py:1: DtypeWarning: Columns (11,12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("out.csv")

In [51]:
df.head()

,Unnamed: 0.1,Unnamed: 0,id,anio_levantamiento,conglomerado,sitio,condicion,especie_id,familia,genero,epiteto,categoria_infra,infraespecie,numero_arbol,numero_tallo,tallos,diametro,altura,is_predicted,latitud,longitud,clave_ecoregion_n2,clave_bur,referencia_1,referencia_2,user_id,created_at,updated_at,grado_putrefaccion,clave_ecoregion_n1,clave_ecoregion_n3,clave_ecoregion_n4,estado_inegi,estado,edad
0,0,2886148.0,2886174.0,2016.0,50760.0,1.0,Vivo,NaN,Malvaceae,Hampea,trilobata,NaN,NaN,14.0,16.0,NaN,8.3,6.4,0.0,20.622,-87.336694,15.2,SMQ,493302.0,16.0,NaN,NaN,NaN,NaN,15.0,15.2.2,15.2.2.2,23.0,Quintana Roo,NaN
1,1,2886149.0,2886175.0,2016.0,50760.0,1.0,Vivo,NaN,Nyctaginaceae,Neea,psychotrioides,NaN,NaN,21.0,23.0,NaN,10.4,8.6,0.0,20.622,-87.336694,15.2,SMQ,493309.0,23.0,NaN,NaN,NaN,NaN,15.0,15.2.2,15.2.2.2,23.0,Quintana Roo,NaN
2,2,2886150.0,2886176.0,2016.0,50760.0,1.0,Vivo,NaN,Fabaceae,Lysiloma,latisiliquum,NaN,NaN,29.0,34.0,NaN,32.8,10.3,0.0,20.622,-87.336694,15.2,SMQ,493320.0,34.0,NaN,NaN,NaN,NaN,15.0,15.2.2,15.2.2.2,23.0,Quintana Roo,NaN
3,3,2886151.0,2886177.0,2016.0,50760.0,1.0,Vivo,NaN,Malvaceae,Luehea,speciosa,NaN,NaN,35.0,40.0,NaN,8.2,7.9,0.0,20.622,-87.336694,15.2,SMQ,493326.0,40.0,NaN,NaN,NaN,NaN,15.0,15.2.2,15.2.2.2,23.0,Quintana Roo,NaN
4,4,2886152.0,2886178.0,2016.0,50760.0,1.0,Vivo,NaN,Sapotaceae,Sideroxylon,salicifolium,NaN,NaN,44.0,49.0,NaN,9.8,6.8,0.0,20.622,-87.336694,15.2,SMQ,493335.0,49.0,NaN,NaN,NaN,NaN,15.0,15.2.2,15.2.2.2,23.0,Quintana Roo,NaN

In [23]:
df.is_predicted.value_counts()

is_predicted
0.0    831331
Name: count, dtype: int64

In [52]:
df.is_predicted.value_counts()

is_predicted
0.0    797404
2.0     12800
1.0      1413
Name: count, dtype: int64

In [9]:
df.anio_levantamiento.value_counts().sort_values()

anio_levantamiento
2004     57198
2018     70822
2017     97781
2014    124222
2019    137663
2007    220566
2016    257073
2015    267992
2009    278312
2013    291158
2011    293027
2010    295597
2012    298702
2006    349929
2005    677437
Name: count, dtype: int64

In [ ]:
df3 = df[(df.anio_levantamiento >= 2015) & (df.anio_levantamiento <= 2020)]

In [10]:
ciclo1 = df[(df.anio_levantamiento >= 2005) & (df.anio_levantamiento <= 2008)]

In [12]:
ciclo1.to_csv("csvs/ciclo_1.csv",index=False)